[package]
name = "dotlocal_toggle"
version = "1.0.0"
edition = "2021"

[dependencies]
registry = "1.3"
anyhow = "1.0"

[dependencies.windows]
version = "0.60"
features = [
    "Win32_UI_WindowsAndMessaging"
]

[build-dependencies]
embed-resource = "2.4"